const cinnostiTyden = [
  {
    name: "Kuchyň",
    time: 60,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Uklidit krámy v obýváku",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Prach v obýváku",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Podlaha v obýváku",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Koupelna",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Záchod",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Prach v ložnici",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Prach v chodbe",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Podlaha v chodbě i v chodbičce nahoře",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Podlaha v kuchyni",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Za dveřmi a parapety zvenku",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Odnést plasty, sklo a papír",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Prach a podlaha na verandě",
    time: 15,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Objednat jídlo",
    time: 40,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Převléct postele v ložnici",
    time: 30,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Převléct postel u Kuby",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Převléct postel u Matěje",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Uklidit jídlo",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Uklidit krámy z chodby",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Kubův pokoj",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Matějův pokoj",
    time: 20,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Podlaha v ložnici",
    time: 10,
    completed: false,
    who: undefined,
    tyden: true,
  },
  {
    name: "Schody do sklepa",
    time: 15,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Prát, věšet 3 pračky",
    time: 30,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Žehlit, uklízet prádlo",
    time: 45,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Vařit oběd - sobota",
    time: 45,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Vařit večeři - sobota",
    time: 30,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Vařit oběd - neděle",
    time: 45,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Vařit večeři nebo chystat svačiny - neděle",
    time: 30,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Zalít kytky",
    time: 10,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Posekat trávu vlevo",
    time: 60,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Posekat trávu vpravo",
    time: 60,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Uklidit sklepní pokoj",
    time: 30,
    completed: false,
    who: undefined as unknown,
    tyden: true,
  },
  {
    name: "Plánovat úklid",
    time: 30,
    completed: false,
    who: "máma",
    tyden: true,
  },
  {
    name: "Organizovat kroužky, doktory, školu atd",
    time: 60,
    completed: false,
    who: "máma",
    tyden: true,
  },
  {
    name: "Opravy domu 1",
    time: 60,
    completed: false,
    who: "táta",
    tyden: true,
  },
  {
    name: "Opravy domu 2",
    time: 120,
    completed: false,
    who: "táta",
    tyden: true,
  },
];

export default cinnostiTyden;
